services:
  match:
    build:
      context: .
      dockerfile: Dockerfile.match
    image: chess-bots:match
    environment:
      - STOCKFISH_PATH=stockfish
      - RUNS_DIR=/runs
    volumes:
      - ./runs:/runs
      - ./logs:/logs
    command: ["python", "-u", "arena.py"]

  tournament:
    build:
      context: .
      dockerfile: Dockerfile.match
    image: chess-bots:tournament
    environment:
      - STOCKFISH_PATH=stockfish
    volumes:
      - ./output:/output
      - ./logs:/logs
    command: [
      "python", "-u", "scripts/tournament.py",
      "--mode", "rr",
      "--bo", "3",
      "--clock", "3|0",
      "--tiebreaks", "off"
    ]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chess-bots:web
    environment:
      - FLASK_DEBUG=0
      - RUNS_DIR=/runs
      - STOCKFISH_PATH=stockfish
      - HEATMAP_DIR=/heatmap_visualizations
    volumes:
      - ./runs:/runs
      - ./heatmap_visualizations:/heatmap_visualizations
      - ./output:/output
      - ./logs:/logs
    ports:
      - "5000:5000"
    command: ["python", "-u", "run_web_server.py"]
