# Configuration for neural network usage
# use_dummy_model: when true, TorchNet will initialise with zero weights
use_dummy_model: false
# weights: optional path to a trained model's state_dict
weights: chess_ai/nn/simple_model.pth
