name: CI

on:
  push:
  pull_request:

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python tests
        run: pytest
      - name: Generate examples
        run: python examples/integration_example.py > examples/example_output.txt
      - name: Upload examples
        uses: actions/upload-artifact@v4
        with:
          name: generated-examples
          path: examples/example_output.txt

  r-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::testthat
          cache-version: 1
      - name: Run R tests
        run: Rscript -e 'testthat::test_dir(".", reporter="summary")'
