name: tests

on:
  push:
  pull_request:

jobs:
  vendor-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run vendor import test
        env:
          PYTHONPATH: ${{ github.workspace }}/vendors:${PYTHONPATH}
        run: pytest tests/test_vendor_imports.py -q
